[2016-03-30 20:21:54] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /admin" (uncaught exception) at C:\xampp\htdocs\silex_end\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin\" at C:\\xampp\\htdocs\\silex_end\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/admin\". at C:\\xampp\\htdocs\\silex_end\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-03-30 20:21:58] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /yonetim" (uncaught exception) at C:\xampp\htdocs\silex_end\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /yonetim\" at C:\\xampp\\htdocs\\silex_end\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/yonetim\". at C:\\xampp\\htdocs\\silex_end\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-03-30 21:58:30] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (from "http://ticked-silex-project.dev/") (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://ticked-silex-project.dev/\") at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-03-30 21:58:37] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /favicon.ico" (from "http://ticked-silex-project.dev/") (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://ticked-silex-project.dev/\") at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 09:53:14] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:15] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:16] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:16] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:16] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:16] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:17] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:17] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:53:48] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /login" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/login\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 09:54:08] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 09:54:09] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 10:08:26] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 10:17:25] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 10:17:26] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 10:17:39] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 12:06:02] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:38] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:53] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:53] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:54] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:54] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:55] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:55] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:55] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:55] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:55] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:39:56] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:40:03] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:40:04] app.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM post':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM post':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ticket.post' doesn't exist at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2016-04-01 12:42:57] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:58] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:59] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:59] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:59] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:59] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:59] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:42:59] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:43:00] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 12:43:00] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:08:38] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 13:08:53] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:15:01] app.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "homepage" as such route does not exist.") in "layout.html.twig" at line 26. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 396 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"homepage\" as such route does not exist.\") in \"layout.html.twig\" at line 26. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:396, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"homepage\" as such route does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Generator\\UrlGenerator.php:130)"} []
[2016-04-01 13:15:04] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /login" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/login\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 13:15:06] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /login" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/login\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 13:15:20] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:15:25] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:01] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:02] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:02] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:02] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:03] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:03] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:04] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:22] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:23] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:23] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:23] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:16:23] app.CRITICAL: Twig_Error_Runtime: Variable "error" does not exist in "login.html.twig" at line 9 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Template.php line 436 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist in \"login.html.twig\" at line 9 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Template.php:436)"} []
[2016-04-01 13:52:48] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params ["example", "changeme", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params [\"example\", \"changeme\", null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 13:53:25] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params ["example", "changeme", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params [\"example\", \"changeme\", null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 13:53:27] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params ["example", "changeme", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params [\"example\", \"changeme\", null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 13:54:05] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params ["example", "changeme", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params [\"example\", \"changeme\", null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 13:54:57] app.CRITICAL: Symfony\Component\Form\Exception\OutOfBoundsException: Child "subformemail" does not exist. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\Form.php line 969 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\OutOfBoundsException(code: 0): Child \"subformemail\" does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\Form.php:969)"} []
[2016-04-01 13:55:10] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params ["example", "changeme", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (username, passsword, id) VALUES (?, ?, ?)' with params [\"example\", \"changeme\", null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 13:55:50] app.CRITICAL: Symfony\Component\Form\Exception\AlreadySubmittedException: A form can only be submitted once (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\Form.php line 504 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\AlreadySubmittedException(code: 0): A form can only be submitted once at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\Form.php:504)"} []
[2016-04-01 14:07:37] app.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO form (subformemail1	, subformtext1, text1) VALUES (?, ?, ?)' with params [null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO form (subformemail1\t, subformtext1, text1) VALUES (?, ?, ?)' with params [null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 14:12:58] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (form) VALUES (?)' with params [{"Ticket-Form":{"subformemail1":"em@mail.com","subformtext1":"ggg"},"text1":"dfgdf","text2":"fdg","text3":"dfg","submit":"","_token":"f-zuQNPvLxpTDu6X4NosxrGSazzJXfLygRkR_L5Q45o"}]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'form' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (form) VALUES (?)' with params [{\"Ticket-Form\":{\"subformemail1\":\"em@mail.com\",\"subformtext1\":\"ggg\"},\"text1\":\"dfgdf\",\"text2\":\"fdg\",\"text3\":\"dfg\",\"submit\":\"\",\"_token\":\"f-zuQNPvLxpTDu6X4NosxrGSazzJXfLygRkR_L5Q45o\"}]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'form' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'form' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'form' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 14:13:13] app.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO form (0) VALUES (?)' with params [{"form":{"Ticket-Form":{"subformemail1":"em@mail.com","subformtext1":"ggg"},"text1":"dfgdf","text2":"fdg","text3":"dfg","submit":"","_token":"f-zuQNPvLxpTDu6X4NosxrGSazzJXfLygRkR_L5Q45o"}}]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) VALUES ('Array')' at line 1 (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO form (0) VALUES (?)' with params [{\"form\":{\"Ticket-Form\":{\"subformemail1\":\"em@mail.com\",\"subformtext1\":\"ggg\"},\"text1\":\"dfgdf\",\"text2\":\"fdg\",\"text3\":\"dfg\",\"submit\":\"\",\"_token\":\"f-zuQNPvLxpTDu6X4NosxrGSazzJXfLygRkR_L5Q45o\"}}]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) VALUES ('Array')' at line 1 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) VALUES ('Array')' at line 1 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) VALUES ('Array')' at line 1 at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 14:21:56] app.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO form (subformemail1	, subformtext1, text1) VALUES (?, ?, ?)' with params [null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO form (subformemail1\t, subformtext1, text1) VALUES (?, ?, ?)' with params [null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subformemail1' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 14:24:08] app.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO form (name) VALUES (?)' with params [null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO form (name) VALUES (?)' with params [null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 14:27:49] app.CRITICAL: InvalidArgumentException: Identifier "subformemail1" is not defined. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\pimple\pimple\lib\Pimple.php line 78 {"exception":"[object] (InvalidArgumentException(code: 0): Identifier \"subformemail1\" is not defined. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\pimple\\pimple\\lib\\Pimple.php:78)"} []
[2016-04-01 14:55:03] app.CRITICAL: Symfony\Component\Form\Exception\OutOfBoundsException: Child "subformemail1" does not exist. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\Form.php line 969 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\OutOfBoundsException(code: 0): Child \"subformemail1\" does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\Form.php:969)"} []
[2016-04-01 14:55:30] app.CRITICAL: Symfony\Component\Form\Exception\OutOfBoundsException: Child "subformtext1" does not exist. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\Form.php line 969 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\OutOfBoundsException(code: 0): Child \"subformtext1\" does not exist. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\Form.php:969)"} []
[2016-04-01 15:06:54] app.CRITICAL: Symfony\Component\Form\Exception\InvalidArgumentException: Could not load type "Category" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\FormRegistry.php line 92 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"Category\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\FormRegistry.php:92)"} []
[2016-04-01 15:08:15] app.CRITICAL: Symfony\Component\Form\Exception\InvalidArgumentException: Could not load type "forms" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\FormRegistry.php line 92 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"forms\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\FormRegistry.php:92)"} []
[2016-04-01 15:09:50] app.CRITICAL: Symfony\Component\Form\Exception\InvalidArgumentException: The name "başlık" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":"). (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\form\FormConfigBuilder.php line 897 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): The name \"başlık\" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores (\"_\"), hyphens (\"-\") and colons (\":\"). at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\form\\FormConfigBuilder.php:897)"} []
[2016-04-01 15:20:29] app.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO forms_ticket (user_id, subject, content, level, file) VALUES (?, ?, ?, ?, ?)' with params [1, "bilgisyar\u0131m \u00e7al\u0131\u015fm\u0131yor", "destek laz\u0131m", "\u00e7ok \u00f6neml,", null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'file' cannot be null (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO forms_ticket (user_id, subject, content, level, file) VALUES (?, ?, ?, ?, ?)' with params [1, \"bilgisyar\\u0131m \\u00e7al\\u0131\\u015fm\\u0131yor\", \"destek laz\\u0131m\", \"\\u00e7ok \\u00f6neml,\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'file' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'file' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'file' cannot be null at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-04-01 18:05:32] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:33] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:33] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:33] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:33] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:34] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:34] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:34] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:34] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:05:34] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:06:05] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:06:06] app.CRITICAL: Twig_Error_Syntax: Unexpected "}" in "layout.html.twig" at line 34. (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\twig\twig\lib\Twig\Lexer.php line 259 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected \"}\" in \"layout.html.twig\" at line 34. at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\twig\\twig\\lib\\Twig\\Lexer.php:259)"} []
[2016-04-01 18:48:32] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /testLogin" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /testLogin\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/testLogin\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 18:50:23] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /testLogin" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /testLogin\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/testLogin\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
[2016-04-01 18:50:24] app.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /testLogin" (uncaught exception) at C:\xampp\htdocs\Ticked_silex_project\vendor\symfony\http-kernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /testLogin\" at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/testLogin\". at C:\\xampp\\htdocs\\Ticked_silex_project\\vendor\\symfony\\routing\\Matcher\\UrlMatcher.php:98)"} []
